[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
    X-Content-Type-Options = "nosniff"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/master-items.json"
  [headers.values]
    Cache-Control = "public, max-age=3600"
